apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  selector:
    app: taskmanager
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
